// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Music.Models;

#nullable disable

namespace Web_Music.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250322125359_UpdateAlbumTable")]
    partial class UpdateAlbumTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Music.Models.Album", b =>
                {
                    b.Property<int>("MaAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAlbum"));

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCaSi")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayPhatHanh")
                        .HasColumnType("date");

                    b.Property<string>("TenAlbum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaAlbum");

                    b.HasIndex("MaCaSi");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Web_Music.Models.BaiHat", b =>
                {
                    b.Property<int>("MaBaiHat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiHat"));

                    b.Property<string>("AnhBia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LuotNghe")
                        .HasColumnType("int");

                    b.Property<int?>("MaAlbum")
                        .HasColumnType("int");

                    b.Property<int>("MaCaSi")
                        .HasColumnType("int");

                    b.Property<int>("MaTheLoai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBaiHat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("ThoiLuong")
                        .HasColumnType("time");

                    b.HasKey("MaBaiHat");

                    b.HasIndex("MaAlbum");

                    b.HasIndex("MaCaSi");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("BaiHats");
                });

            modelBuilder.Entity("Web_Music.Models.CaSi", b =>
                {
                    b.Property<int>("MaCaSi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCaSi"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCaSi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCaSi");

                    b.ToTable("CaSis");
                });

            modelBuilder.Entity("Web_Music.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Web_Music.Models.TheLoai", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTheLoai"));

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoais");
                });

            modelBuilder.Entity("Web_Music.Models.Album", b =>
                {
                    b.HasOne("Web_Music.Models.CaSi", "MaCaSiNavigation")
                        .WithMany("Albums")
                        .HasForeignKey("MaCaSi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaCaSiNavigation");
                });

            modelBuilder.Entity("Web_Music.Models.BaiHat", b =>
                {
                    b.HasOne("Web_Music.Models.Album", "MaAlbumNavigation")
                        .WithMany("BaiHats")
                        .HasForeignKey("MaAlbum");

                    b.HasOne("Web_Music.Models.CaSi", "MaCaSiNavigation")
                        .WithMany("BaiHats")
                        .HasForeignKey("MaCaSi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Music.Models.TheLoai", "MaTheLoaiNavigation")
                        .WithMany("BaiHats")
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaAlbumNavigation");

                    b.Navigation("MaCaSiNavigation");

                    b.Navigation("MaTheLoaiNavigation");
                });

            modelBuilder.Entity("Web_Music.Models.Album", b =>
                {
                    b.Navigation("BaiHats");
                });

            modelBuilder.Entity("Web_Music.Models.CaSi", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("BaiHats");
                });

            modelBuilder.Entity("Web_Music.Models.TheLoai", b =>
                {
                    b.Navigation("BaiHats");
                });
#pragma warning restore 612, 618
        }
    }
}
